"""Telegram notifier with Gemini-generated fun VPN facts.

Sends a message to a Telegram chat after each pipeline run with:
- Config count and countries
- A fun VPN/privacy fact generated by Gemini
- Subscription URL

Usage (standalone, from CLI):
    python -m src.notify.telegram --configs 50 --countries "DE FI NL US"

Usage (imported):
    from src.notify.telegram import send_notification
    send_notification(configs_count=50, countries="DE FI NL US")
"""

from __future__ import annotations

import argparse
import html
import json
import logging
import os
import sys
import socket
import urllib.request
import urllib.error

logger = logging.getLogger(__name__)

# Telegram bot tokens have format: <digits>:<alphanumeric_hash>
# e.g. "123456789:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
_TOKEN_MIN_LEN = 20

# LLM endpoint — OpenAI-compatible. DashScope (Alibaba) qwen-flash is fast and free.
_LLM_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"
_LLM_MODEL = "qwen-flash"

# Default subscription URL (kept in one place — referenced by both the
# send_notification() default and the CLI --url default below).
_SUBSCRIPTION_URL = (
    "https://raw.githubusercontent.com/Moonishe/vpnparser/main/output/subscription.txt"
)

_BOT_INTRO = (
    "🤖 Я — vpnparser бот от @dutysissy\n"
    "📡 Парсю публичные VPN конфиги каждый час\n"
    "🔗 https://github.com/Moonishe/vpnparser"
)

_FACT_PROMPT = (
    "Сгенерируй ОДИН короткий забавный факт о VPN, приватности или "
    "интернет-цензуре. Не больше 2 предложений. На русском. "
    "С лёгким юмором. Без emoji. Просто текст."
)

_FACT_HISTORY_FILE = "facts_history.json"
_FACT_HISTORY_MAX = 50  # keep last 50 facts

_FACT_FALLBACK_NO_KEY = (
    "VPN расшифровывается как Very Private Network "
    "(шутка, на самом деле Virtual Private Network)."
)

# Multiple fallback facts — rotate so they don't repeat when Gemini is unavailable.
_FACT_FALLBACKS = [
    "Первый VPN был создан в 1996 году компанией Microsoft. С тех пор мы прячемся от провайдеров уже 30 лет.",
    "Слово VPN на латыни звучит бы как 'privatus iter', что примерно переводится как 'тайный путь'. Римляне бы оценили.",
    "Если бы VPN был человеком, он бы носил плащ, шляпу и говорил бы 'я не был здесь' каждому встречному.",
    "В некоторых странах за использование VPN можно получить штраф. В других — просто нормальный интернет.",
    "VPN не делает вас анонимным. Он делает вас 'труднодоступным'. Это как прятаться за ширмой — видно ноги, но не лицо.",
    "Самый популярный пароль для WiFi в 2024 году — '12345678'. VPN хотя бы пытается вас защитить.",
    "Без VPN ваш провайдер знает каждый сайт, который вы посещаете. С VPN — он знает только что вы зашли в туннель.",
    "VPN-протокол WireGuard состоит всего из 4000 строк кода. OpenVPN — из 70 000. Иногда меньше — значит лучше.",
    "Первый протокол VPN (PPTP) был создан Microsoft в 1996 году. Сейчас его не рекомендуют даже сами разработчики.",
    "Tor и VPN — это не одно и то же. Tor — это лук, VPN — это труба. Оба прячут, но по-разному.",
    "В Китае более 700 миллионов пользователей VPN. Это больше, чем население всей Европы.",
    "VPN-серверы в Швейцарии и Исландии популярны из-за строгих законов о приватности. Банки данных — не банки денег.",
    "Самый дорогой VPN стоит около $15 в месяц. Самый дешёвый — ваш сосед с OpenVPN на Raspberry Pi.",
    "Слово 'туннелирование' в VPN — это не метафора. Ваш трафик реально упаковывается в другой пакет, как матрёшка.",
    "Если вы используете бесплатный VPN, вы — товар. Ваш данные могут продаваться. К счастью, наш парсер находит бесплатные серверы, а не бесплатный VPN-сервис.",
]

# Country flag emojis + Russian names for output.
_COUNTRY_INFO = {
    "DE": ("🇩🇪", "Германия"),
    "FI": ("🇫🇮", "Финляндия"),
    "NL": ("🇳🇱", "Нидерланды"),
    "US": ("🇺🇸", "США"),
    "GB": ("🇬🇧", "Великобритания"),
    "FR": ("🇫🇷", "Франция"),
    "JP": ("🇯🇵", "Япония"),
    "SG": ("🇸🇬", "Сингапур"),
    "CA": ("🇨🇦", "Канада"),
    "AE": ("🇦🇪", "ОАЭ"),
    "TR": ("🇹🇷", "Турция"),
    "ID": ("🇮🇩", "Индонезия"),
    "RU": ("🇷🇺", "Россия"),
    "PL": ("🇵🇱", "Польша"),
    "SE": ("🇸🇪", "Швеция"),
    "CH": ("🇨🇭", "Швейцария"),
    "AT": ("🇦🇹", "Австрия"),
    "ES": ("🇪🇸", "Испания"),
    "IT": ("🇮🇹", "Италия"),
    "AU": ("🇦🇺", "Австралия"),
    "KR": ("🇰🇷", "Корея"),
    "HK": ("🇭🇰", "Гонконг"),
    "TW": ("🇹🇼", "Тайвань"),
    "IN": ("🇮🇳", "Индия"),
    "TH": ("🇹🇭", "Таиланд"),
    "VN": ("🇻🇳", "Вьетнам"),
    "BR": ("🇧🇷", "Бразилия"),
    "MX": ("🇲🇽", "Мексика"),
}

# Subscription URLs — combined + split outputs.
_SUBSCRIPTION_URLS = {
    "combined": "https://raw.githubusercontent.com/Moonishe/vpnparser/main/output/subscription.txt",
    "blacklist": "https://raw.githubusercontent.com/Moonishe/vpnparser/main/output/subscription-blacklist.txt",
    "whitelist": "https://raw.githubusercontent.com/Moonishe/vpnparser/main/output/subscription-whitelist.txt",
}
_SUBSCRIPTION_URL = _SUBSCRIPTION_URLS["combined"]


def _count_countries_from_file(filepath: str) -> dict[str, int]:
    """Decode subscription.txt and count configs per country.

    Returns a dict {country_code: count}, sorted by count descending.
    Returns empty dict if file can't be read or decoded.
    """
    from collections import Counter
    from src.validators.country_filter import detect_country

    try:
        raw = open(filepath, "r", encoding="utf-8").read().strip()
    except Exception:
        return {}

    try:
        import base64

        text = base64.b64decode(raw).decode("utf-8")
    except Exception:
        text = raw

    lines = [l.strip() for l in text.strip().split("\n") if "://" in l]

    countries = Counter()
    for l in lines:
        # Skip watermark
        if "0.0.0.0" in l and "vmess://" in l:
            continue
        # Extract remark from fragment
        remark = ""
        if "#" in l:
            from urllib.parse import unquote

            remark = unquote(l.split("#")[-1].strip())
        # Extract host from link body
        host = ""
        body = l.split("://", 1)[1] if "://" in l else ""
        if "@" in body:
            host = body.split("@", 1)[1].split(":")[0].split("?")[0].strip("[]")
        # Use detect_country from country_filter (same logic as pipeline)
        code = detect_country(remark, host)
        if code:
            countries[code] += 1

    return dict(countries.most_common())


def _load_facts_history() -> list[str]:
    """Load previously generated facts from cache file."""
    try:
        with open(_FACT_HISTORY_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data if isinstance(data, list) else []
    except (FileNotFoundError, json.JSONDecodeError):
        return []
    except Exception:
        return []


def _save_fact(fact: str) -> None:
    """Append fact to history file, keeping last _FACT_HISTORY_MAX entries."""
    history = _load_facts_history()
    history.append(fact)
    history = history[-_FACT_HISTORY_MAX:]
    try:
        with open(_FACT_HISTORY_FILE, "w", encoding="utf-8") as f:
            json.dump(history, f, ensure_ascii=False, indent=2)
    except Exception as exc:
        logger.warning("Could not save fact history: %s", exc)


def _call_gemini(api_key: str, prompt: str) -> str | None:
    """Single Gemini API call. Returns text or None on failure."""
    try:
        body = json.dumps(
            {
                "model": _LLM_MODEL,
                "messages": [
                    {
                        "role": "system",
                        "content": "Ты — забавный ассистент, который знает факты о VPN. Отвечай кратко на русском.",
                    },
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.9,
                "max_tokens": 150,
            }
        ).encode("utf-8")

        req = urllib.request.Request(
            _LLM_URL,
            data=body,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
                "User-Agent": "vpnparser/1.0",
            },
            method="POST",
        )

        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            choices = data.get("choices") or []
            if not choices:
                return None
            content = choices[0].get("message", {}).get("content")
            if not isinstance(content, str) or not content.strip():
                return None
            return " ".join(content.split())
    except Exception as exc:
        logger.warning("Gemini API call failed: %s", exc)
        return None


def _generate_fun_fact(api_key: str) -> str:
    """Call Gemini API to generate a fun VPN fact.

    Loads history of previous facts, tells Gemini not to repeat them,
    retries up to 3 times if the generated fact is a duplicate.
    Saves the new fact to history.
    Returns a fallback if API fails or no API key.
    """
    if not api_key or not str(api_key).strip():
        # No API key — use rotating fallback, not the same static one every time.
        import random

        history = _load_facts_history()
        all_fallbacks = [_FACT_FALLBACK_NO_KEY] + _FACT_FALLBACKS
        available = [
            f
            for f in all_fallbacks
            if f.lower().strip() not in {h.lower().strip() for h in history}
        ]
        if not available:
            available = all_fallbacks
        fallback = random.choice(available)
        _save_fact(fallback)
        return fallback

    api_key = str(api_key).strip()
    history = _load_facts_history()

    # Build prompt with "don't repeat" list.
    dont_repeat = ""
    if history:
        recent = history[-10:]  # show last 10 to Gemini
        dont_repeat = "\n\nНе повторяй эти факты:\n" + "\n".join(
            f"- {h}" for h in recent
        )

    prompt = _FACT_PROMPT + dont_repeat

    # Try up to 3 times to get a non-duplicate fact.
    for attempt in range(3):
        fact = _call_gemini(api_key, prompt)
        if fact is None:
            break
        # Check if it's a duplicate (case-insensitive, stripped).
        fact_lower = fact.lower().strip()
        if any(fact_lower == h.lower().strip() for h in history):
            logger.info(
                "Gemini returned duplicate fact (attempt %d) — retrying", attempt + 1
            )
            continue
        # Found a unique fact — save and return.
        _save_fact(fact)
        return fact

    # All retries failed or API unavailable — pick a fallback not in history.
    import random

    available = [
        f
        for f in _FACT_FALLBACKS
        if f.lower().strip() not in {h.lower().strip() for h in history}
    ]
    if not available:
        # All fallbacks used — pick random one.
        available = _FACT_FALLBACKS
    fallback = random.choice(available)
    _save_fact(fallback)
    return fallback


def _send_telegram(token: str, chat_id: str, text: str) -> bool:
    """Send a message to Telegram via Bot API.

    Returns True on success, False on failure.
    """
    # Fail fast on empty credentials — otherwise we make a guaranteed-to-fail
    # network request that blocks for the full timeout (10s) before returning
    # False.  A negative ``chat_id`` is legitimate (Telegram groups/supergroups),
    # so only emptiness is rejected here.
    if not token or not str(token).strip() or not chat_id or not str(chat_id).strip():
        logger.warning("Telegram send skipped — empty token or chat_id")
        return False

    token = str(token).strip()
    chat_id = str(chat_id).strip()
    text = text or ""

    # Telegram sendMessage rejects text longer than 4096 chars with a 400.
    # Truncate defensively — the fact is bounded by max_tokens, but a future
    # prompt change or a huge countries list could otherwise blow the limit.
    if len(text) > 4096:
        text = text[:4093] + "..."
        logger.warning("Telegram message truncated to 4096 chars")

    # Validate token format — fail fast instead of a 10s network timeout.
    # Telegram bot tokens: 123456789:ABC-DEF1234ghIkl-zyx57W2v1u123ew11
    if (
        ":" not in token
        or len(token) < _TOKEN_MIN_LEN
        or not token.split(":", 1)[0].isdigit()
    ):
        logger.warning("Telegram token has invalid format — expected '<digits>:<hash>'")
        return False

    try:
        data = json.dumps(
            {
                "chat_id": chat_id,
                "text": text,
                "parse_mode": "HTML",
            }
        ).encode("utf-8")

        req = urllib.request.Request(
            f"https://api.telegram.org/bot{token}/sendMessage",
            data=data,
            headers={
                "Content-Type": "application/json",
                "User-Agent": "vpnparser/1.0",
            },
            method="POST",
        )

        with urllib.request.urlopen(req, timeout=10) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            return result.get("ok", False)
    except urllib.error.HTTPError as exc:
        # HTTPError is file-like — read Telegram's error description.
        try:
            body = exc.read().decode("utf-8", errors="replace")[:200]
        except Exception:
            body = ""
        logger.warning("Telegram API returned HTTP %d: %s", exc.code, body)
        return False
    except urllib.error.URLError as exc:
        if isinstance(exc.reason, (socket.timeout, TimeoutError)):
            logger.warning("Telegram send timed out after 10s — API unreachable")
        else:
            logger.warning("Telegram send network error: %s", exc.reason)
        return False
    except Exception as exc:
        logger.warning("Telegram send failed unexpectedly: %s", exc)
        return False


def send_notification(
    configs_count: int,
    countries: str = "DE FI NL US GB FR JP SG CA",
    subscription_url: str = _SUBSCRIPTION_URL,
    subscription_file: str = "",
) -> bool:
    """Send a Telegram notification with config count + fun fact.

    Reads TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, LLM_API_KEY from env.
    If subscription_file is provided, parses it for per-country breakdown.
    Returns True if sent, False if skipped or failed.
    """
    token = (os.environ.get("TELEGRAM_BOT_TOKEN") or "").strip()
    chat_id = (os.environ.get("TELEGRAM_CHAT_ID") or "").strip()

    if not token or not chat_id:
        logger.info("Telegram credentials not set — skipping notification")
        return False

    # Normalise inputs.
    if not isinstance(configs_count, int):
        try:
            configs_count = int(configs_count)
        except (TypeError, ValueError):
            configs_count = 0
    if configs_count < 0:
        configs_count = 0

    subscription_url = (subscription_url or "").strip() or "—"

    # Get per-country breakdown from subscription file if available.
    country_counts: dict[str, int] = {}
    if subscription_file:
        country_counts = _count_countries_from_file(subscription_file)

    # Generate fun fact via Gemini.
    api_key = os.environ.get("LLM_API_KEY", "")
    fact = _generate_fun_fact(api_key)

    # Build country breakdown lines.
    if country_counts:
        country_lines = []
        for code, count in country_counts.items():
            flag, name = _COUNTRY_INFO.get(code, ("🌍", code))
            country_lines.append(f"  {flag} {name}: {count}")
        country_section = "\n".join(country_lines)
    else:
        country_section = html.escape(countries)

    # Build message.
    message = (
        f"Конфиг обновился, обновите конфигурацию.\n"
        f"Страны которые обновились:\n"
        f"{country_section}\n"
        f"\n"
        f"🔮 Факт: {html.escape(fact)}\n"
        f"\n"
        f"📋 Подписки:\n"
        f"  🔗 Комбинированная: {html.escape(_SUBSCRIPTION_URLS['combined'])}\n"
        f"  ⚫ Чёрный список: {html.escape(_SUBSCRIPTION_URLS['blacklist'])}\n"
        f"  ⚪ Белый список: {html.escape(_SUBSCRIPTION_URLS['whitelist'])}"
    )

    return _send_telegram(token, chat_id, message)


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Send Telegram notification")
    parser.add_argument("--configs", type=int, required=True, help="Number of configs")
    parser.add_argument("--countries", type=str, default="DE FI NL US GB FR JP SG CA")
    parser.add_argument(
        "--url",
        type=str,
        default=_SUBSCRIPTION_URL,
    )
    parser.add_argument(
        "--file",
        type=str,
        default="output/subscription.txt",
        help="Path to subscription.txt for per-country breakdown",
    )
    args = parser.parse_args()

    if args.configs < 0:
        parser.error(f"--configs must be >= 0 (got {args.configs})")

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    ok = send_notification(
        configs_count=args.configs,
        countries=args.countries,
        subscription_url=args.url,
        subscription_file=args.file,
    )
    if ok:
        logger.info("Notification sent")
        return 0
    else:
        logger.info("Notification skipped or failed (non-fatal)")
        return 0  # Non-fatal — don't fail the workflow.


if __name__ == "__main__":
    sys.exit(main())
