"""Telegram notifier with Gemini-generated fun VPN facts.

Sends a message to a Telegram chat after each pipeline run with:
- Config count and countries
- A fun VPN/privacy fact generated by Gemini
- Subscription URL

Usage (standalone, from CLI):
    python -m src.notify.telegram --configs 50 --countries "DE FI NL US"

Usage (imported):
    from src.notify.telegram import send_notification
    await send_notification(configs_count=50, countries="DE FI NL US")
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
import urllib.request
import urllib.error

logger = logging.getLogger(__name__)

# Gemini OpenAI-compatible endpoint.
_GEMINI_URL = "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"

_BOT_INTRO = (
    "🤖 Я — vpnparser бот от @Moonishe\n"
    "📡 Парсю публичные VPN конфиги каждый час\n"
    "🔗 https://github.com/Moonishe/vpnparser"
)

_FACT_PROMPT = (
    "Сгенерируй ОДИН короткий забавный факт о VPN, приватности или "
    "интернет-цензуре. Не больше 2 предложений. На русском. "
    "С лёгким юмором. Без emoji. Просто текст."
)


def _generate_fun_fact(api_key: str) -> str:
    """Call Gemini API to generate a fun VPN fact.

    Returns a plain text fact, or a fallback if API fails.
    """
    if not api_key:
        return "VPN расшифровывается как Very Private Network (шутка, на самом деле Virtual Private Network)."

    try:
        body = json.dumps(
            {
                "model": "gemini-2.0-flash",
                "messages": [
                    {
                        "role": "system",
                        "content": "Ты — забавный ассистент, который знает факты о VPN. Отвечай кратко на русском.",
                    },
                    {"role": "user", "content": _FACT_PROMPT},
                ],
                "temperature": 0.9,
                "max_tokens": 150,
            }
        ).encode("utf-8")

        req = urllib.request.Request(
            _GEMINI_URL,
            data=body,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
            },
            method="POST",
        )

        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            fact = data["choices"][0]["message"]["content"].strip()
            return fact
    except Exception as exc:
        logger.warning("Gemini fact generation failed: %s — using fallback", exc)
        return "Первый VPN был создан в 1996 году компанией Microsoft. С тех пор мы прячемся от провайдеров уже 30 лет."


def _send_telegram(token: str, chat_id: str, text: str) -> bool:
    """Send a message to Telegram via Bot API.

    Returns True on success, False on failure.
    """
    try:
        data = json.dumps(
            {
                "chat_id": chat_id,
                "text": text,
                "parse_mode": "HTML",
            }
        ).encode("utf-8")

        req = urllib.request.Request(
            f"https://api.telegram.org/bot{token}/sendMessage",
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        with urllib.request.urlopen(req, timeout=10) as resp:
            result = json.loads(resp.read().decode("utf-8"))
            return result.get("ok", False)
    except Exception as exc:
        logger.warning("Telegram send failed: %s", exc)
        return False


def send_notification(
    configs_count: int,
    countries: str = "DE FI NL US GB FR JP SG CA",
    subscription_url: str = "https://raw.githubusercontent.com/Moonishe/vpnparser/main/output/subscription.txt",
) -> bool:
    """Send a Telegram notification with config count + fun fact.

    Reads TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, LLM_API_KEY from env.
    Returns True if sent, False if skipped or failed.
    """
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")

    if not token or not chat_id:
        logger.info("Telegram credentials not set — skipping notification")
        return False

    # Generate fun fact via Gemini.
    api_key = os.environ.get("LLM_API_KEY", "")
    fact = _generate_fun_fact(api_key)

    # Build message.
    message = (
        f"{_BOT_INTRO}\n"
        f"\n"
        f"✅ Конфигов: {configs_count}\n"
        f"🌍 Страны: {countries}\n"
        f"🔮 Факт: {fact}\n"
        f"\n"
        f"🔗 {subscription_url}"
    )

    return _send_telegram(token, chat_id, message)


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description="Send Telegram notification")
    parser.add_argument("--configs", type=int, required=True, help="Number of configs")
    parser.add_argument("--countries", type=str, default="DE FI NL US GB FR JP SG CA")
    parser.add_argument(
        "--url",
        type=str,
        default="https://raw.githubusercontent.com/Moonishe/vpnparser/main/output/subscription.txt",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    ok = send_notification(
        configs_count=args.configs,
        countries=args.countries,
        subscription_url=args.url,
    )
    if ok:
        print("Notification sent!")
        return 0
    else:
        print("Notification skipped or failed (non-fatal)")
        return 0  # Non-fatal — don't fail the workflow.


if __name__ == "__main__":
    sys.exit(main())
